---
title: "2025 Final"
subtitle: "https://github.com/bonetati/ENVS-193DS_spring-2025_final"
output: html_document
---

```{r setup, message=FALSE}
library(tidyverse)
library(here)
library(gt) 
library(janitor)
library(readxl)
library(dplyr)
```

1a. 
In part 1, they used a pearson correlation test to compare the relationship between distance from head water and annual total nitrogen load. In part 2, they used a one-way ANOVA to test differences in mean annual nitrogen load between five different sources, urban land, atmospheric deposition, fertilizer, waste water treatment, and grasslands.

1b. To learn more information we could do a post-hoc pairwise comparison test which would identify which of the specific sources differ significantly from each other in average nitrogen load. The second piece of information that would be useful to to have is the group means and standard deviations for each nitrogen source since this would help better understand the differences in nitrogen load between sources. This is important as it provides biological context.

1c.
Part 1: We found that total nitrogen load tends to increase with distance from headwater, suggesting that agricultural runoff accumulates downstream. Using the Pearson correlation test were r = correlation coefficient, p = 0.03, and α = significance level. 
Part 2: We found that average nitrogen load varied significantly among sources, with fertilizer and wastewater treatment appearing to contirbute more nitrogen loads than grasslands or atmospheric deposition. Using the statistical test of a one-way ANOVA were F = test statistic, df = degrees of freedom, p = 0.02, α = significance level.












